import os
from collections.abc import Generator

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import Session, sessionmaker

# Ensure settings can initialize in test runs.
os.environ.setdefault("DATABASE_URL", "sqlite:///./qa_test_bootstrap.db")
os.environ.setdefault("APP_ENV", "test")
os.environ.setdefault("AUTH_TOKEN_SECRET", "test-secret")

from app.db.models import Base, Profile, User  # noqa: E402
from app.db.session import get_db  # noqa: E402
from app.main import app  # noqa: E402


@pytest.fixture()
def db_session(tmp_path) -> Generator[Session, None, None]:
    db_path = tmp_path / "qa_suite.sqlite3"
    engine = create_engine(
        f"sqlite:///{db_path}",
        connect_args={"check_same_thread": False},
    )
    TestingSessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
    Base.metadata.create_all(bind=engine)
    session = TestingSessionLocal()
    try:
        yield session
    finally:
        session.close()
        Base.metadata.drop_all(bind=engine)


@pytest.fixture()
def client(db_session: Session) -> Generator[TestClient, None, None]:
    def _override_get_db():
        yield db_session

    app.dependency_overrides[get_db] = _override_get_db
    with TestClient(app) as test_client:
        yield test_client
    app.dependency_overrides.clear()


@pytest.fixture()
def seeded_profiles(db_session: Session) -> list[Profile]:
    profiles = [
        Profile(
            reg_no="R-001",
            name="Amina",
            gender="Female",
            sect="Shia",
            city="Karachi",
            age=28,
            education="BS CS",
            profession="Engineer",
            category="Syed",
            is_active=True,
        ),
        Profile(
            reg_no="R-002",
            name="Sara",
            gender="Female",
            sect="Sunni",
            city="Lahore",
            age=31,
            education="MBBS",
            profession="Doctor",
            category="Doctor",
            is_active=True,
        ),
        Profile(
            reg_no="R-003",
            name="Ali",
            gender="Male",
            sect="Shia",
            city="Karachi",
            age=33,
            education="MBA",
            profession="Business",
            category="2nd Marriage",
            is_active=True,
        ),
    ]
    db_session.add_all(profiles)
    db_session.commit()
    return profiles


@pytest.fixture()
def active_user(db_session: Session) -> User:
    # password hash generated by auth._hash_password("StrongPass123!")
    user = User(
        full_name="Test User",
        email="tester@example.com",
        password_hash="s+1N9dqAnKBdwImjooY4ugMJhoN/JHkKd2Q2CUkk29xxlX1QIG6qM6Xrsg8D2jlV",
        gender="Male",
        sect="Shia",
        caste="Syed",
        city_country="Karachi, Pakistan",
        is_active=True,
    )
    db_session.add(user)
    db_session.commit()
    db_session.refresh(user)
    return user
